name: autoselect
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - scikit-learn
  - seaborn
  - matplotlib
  - scipy
  - pandas
  - numpy
  - h5py
  - tensorflow
  - xgboost
  - r-base
  - r-ggplot2
  - r-dplyr
  - r-alphasimr
  - r-bglr
  - r-optparse
  - optuna
  - pip
  - pip:
    - skrebate
    - ngboost
